/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_undefined_uvault_UVaultMain */

#ifndef _Included_org_undefined_uvault_UVaultMain
#define _Included_org_undefined_uvault_UVaultMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_undefined_uvault_UVaultMain
 * Method:    generateNewVault
 * Signature: (Ljava/lang/String;[CJ)I
 */
JNIEXPORT jint JNICALL Java_org_undefined_uvault_UVaultMain_generateNewVault
  (JNIEnv *, jclass, jstring, jcharArray, jlong);

/*
 * Class:     org_undefined_uvault_UVaultMain
 * Method:    openVault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_undefined_uvault_UVaultMain_openVault
  (JNIEnv *, jclass);

/*
 * Class:     org_undefined_uvault_UVaultMain
 * Method:    vaultPathExists
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_undefined_uvault_UVaultMain_vaultPathExists
  (JNIEnv *, jclass);

/*
 * Class:     org_undefined_uvault_UVaultMain
 * Method:    fetchVaults
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_undefined_uvault_UVaultMain_fetchVaults
  (JNIEnv *, jclass);

/*
 * Class:     org_undefined_uvault_UVaultMain
 * Method:    closeVault
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_undefined_uvault_UVaultMain_closeVault
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_undefined_uvault_UVaultMain
 * Method:    vaultCommand
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_undefined_uvault_UVaultMain_vaultCommand
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
